name: Publish to Docker Hub

on:
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}