name: Publish to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jcrelling/cnfdemopyapp:latest, jcrelling/cnfdemopyapp:${{ github.sha }}

  change_deployment_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app definition repo
        uses: actions/checkout@v3
        with:
          repository: jcrelling/argocd-demo-app3
          ref: 'main'
          token: ${{ secrets.EXTERNAL_TOKEN }}
      - name: Modify app definition
        run: |
          old_sha=$(grep 'image:' app3.yml|awk -F: '{{ print $3 }}')
          sed -i "s/$old_sha/${{ github.sha }}/g" app3.yml
          cat app3.yml
      - name: Push modification
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated by GitHub Action"
          git push

